### ISSUE TITLE
 exec format error

### ISSUE THREAD

**Issue by janaxhell** [krestaino/sptnr#1]
Hi, I'm trying to deploy the docker-compose.yml, but I'm getting exec error.
My compose looks like this

```
version: "3.8"

services:
  sptnr:
    container_name: sptnr
    image: krestaino/sptnr:latest
    environment:
      - NAV_BASE_URL=https://xxx.xxx.xxx
      - NAV_USER=xxxxxxxx
      - NAV_PASS=xxxxxxxx
      - SPOTIFY_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - SPOTIFY_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/sptnr/logs:/usr/src/app/logs
      
networks:
  omv1:
    external: true
```

I have added omv1 network because I have not enough non-overlapping IPs. 
The first time I ran it I got:

```
root@openmediavault:~# root@openmediavault:~# docker-compose run sptnr
WARN[0000] network default: network.external.name is deprecated. Please set network.name with external: true
[+] Running 9/9
 ✔ sptnr 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                               12.3s
   ✔ 24e221e92a36 Pull complete                                                                                    1.1s
   ✔ 6b9513afbd99 Pull complete                                                                                    0.6s
   ✔ 55ea35dd0432 Pull complete                                                                                    0.9s
   ✔ e544e6fd47b5 Pull complete                                                                                    1.0s
   ✔ 9f311383358c Pull complete                                                                                    1.4s
   ✔ 471c37cf8014 Pull complete                                                                                    3.4s
   ✔ 261624c2de83 Pull complete                                                                                    3.0s
   ✔ 9b17a06ed32b Pull complete                                                                                    2.3s
exec /usr/local/bin/python: exec format error
```

I fixed the syntax of omv1 network like above (some apps want it in a way, some others in another) and in this case all I get is:

```
root@openmediavault:~# docker-compose run sptnr
exec /usr/local/bin/python: exec format error
```

Also tried to add /music to my Navidrome address AND local IP instead of public domain with same result.

EDIT I'm on Open Media Vault 6 x86.
